name = "Simply Optimized"
author = "Foga2H"
version = "1.20.1-12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bb0d0f49842ff04484476016a39faf02939de04f2b2243c7d1e61cb1fbcc2d9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
