name = "Simply Optimized"
author = "Foga2H"
version = "1.20.1-12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26daacb476ee16e2c616d2a2c7c95c77f829b2ef49c670d492f62774367ae04f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
