name = "Simply Optimized"
author = "Foga2H"
version = "1.20.1-12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40254fa04c09b2ad5950a7aec85b64f904dab07a1b88f7c323126b56aedaa5d3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
