# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				arrow = true
				trader_llama = true
				donkey = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				llama = true
				iron_golem = true
				bat = true
				rabbit = true
				cat = true
				zombie = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				potion = true
				turtle = true
				wolf = true
				villager = true
				salmon = true
				wandering_trader = true
				zombie_villager = true
				boat = true
				horse = true
				phantom = true
				llama_spit = true
				cave_spider = true
				glow_squid = true
				witch = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.naturalist]
				robin = true
				bass = true
				snail = true
				firefly = true
				butterfly = true
				duck = true
				snake = true
				sparrow = true

			[light_sources.settings.entities.doapi]
				chair = true

			[light_sources.settings.entities.creeperoverhaul]
				dripstone_creeper = true
				cave_creeper = true

			[light_sources.settings.entities.exlinefurniture]
				entity_sit = true

